language: cpp
compiler: g++
dist: xenial

sudo: required
group: deprecated-2017Q1 

script: 
  - sudo apt-get update
  - make

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-multilib
    - gcc-multilib
    - binutils

